name: tinder_spotify
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev



version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  spotify: ^0.4.0
  cupertino_icons: ^0.1.3
  firebase_core: ^0.5.0+1
  firebase_auth: ^0.18.1+2
  google_sign_in: ^4.5.6
  flutter_webview_plugin: ^0.3.11
  dotenv: ^2.0.0
  http: ^0.12.2
  flutter_web_auth: ^0.2.4
  cloud_firestore: ^0.14.1+3
  provider: ^4.3.2+3
  spotify_sdk: ^1.0.0
  google_fonts: ^1.1.1
  geolocator: ^6.1.13
  image_picker: ^0.6.7+20
  date_time_picker: "^1.1.1"
  tinder_swipecard: ^0.1.0
  clippy_flutter: ^1.1.1




  

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:


  uses-material-design: true
  assets:
    - images/


  fonts:
    - family: StringLabs
      fonts:
        - asset: fonts/Stringlabs.ttf
